### PR TITLE
don't round price since it sometimes causes the order to fail

### PR DESCRIPTION
**Pull request by abmantis**

### CODE REVIEW

**Comment by poupas** [comment]
Hi, thanks for the PR. In what instances is the operation failing? In the past, we had problems because if we did not round the price value, GDAX complained about too much precision. I assume you encountered a case where is was rounding up?

**Comment by abmantis** [comment]
I don't remember for sure (I changed the code a few weeks ago, but only commited today), but I think it was rounding up. It was mostly on ETH/BTC orders IIRC.
I haven't had any issue from the GDAX api yet.

**Comment by poupas** [comment]
That makes sense. In this instance, since the price is coming directly from the order book, I think we should use the value as is, without conversion.

Thanks again.

**Comment by poupas** [comment]
Could you submit another pull request without the `'%f'` conversion? The idea is to just use the value directly:

```
...
order['price'] = eval(order['price'].format(
...
```

**Pull request merged**
